name: Testing on Debian Buster

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
     branches:    
      - main  

env:
  CARGO_TERM_COLOR: always

jobs:
  # Label of the container job
  debian-testing:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-20.04
    # Docker Hub image that `debian-testing` executes in
    container: debian:buster

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: apt-get -y install rustc rust-src rust-gdb cargo libstd-rust-dev libstd-rust-1.41

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

