name: Testing on Ubuntu

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
     branches:    
      - main  

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-testing:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

